#ifndef _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H
#define _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H 1

#define TEGRA_XUSB_PADCTL_PCIE 0
#define TEGRA_XUSB_PADCTL_SATA 1
#define TEGRA_XUSB_PADCTL_USB3_P0 2
#define TEGRA_XUSB_PADCTL_USB3_P1 3
#define TEGRA_XUSB_PADCTL_USB3_P2 4
#define TEGRA_XUSB_PADCTL_USB3_P3 5
#define TEGRA_XUSB_PADCTL_UTMI_P0 6
#define TEGRA_XUSB_PADCTL_UTMI_P1 7
#define TEGRA_XUSB_PADCTL_UTMI_P2 8
#define TEGRA_XUSB_PADCTL_UTMI_P3 9
#define TEGRA_XUSB_PADCTL_HSIC_P0 10
#define TEGRA_XUSB_PADCTL_HSIC_P1 11
#define TEGRA_XUSB_PADCTL_MAX_PHYS 12

#endif /* _DT_BINDINGS_PINCTRL_TEGRA_XUSB_H */
